"""
Django settings for adminApi project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%b@mlq9!tfh&kp)5yn_!^72y+=hdzj4haap6dzk*0(redbg@@!'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "adminApi",    # 后台管理
    'deviceAdmin',    # 设备管理
    'android',      # 应用接口
    'softAdmin',      # 软件管理
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adminApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adminApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_TZ = False

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# debug = False时启用
# DEBUG = False
# STATIC_URL = '/static/'
# STATIC_ROOT = 'static'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, '/static/')
# ]

# debug = True时启用
DEBUG = True
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')    # 'static' 改为 '/static/'
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ========== 新增：日志配置 ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 不禁用已有日志器
    'formatters': {
        # 日志格式：包含 时间、日志级别、文件名、行号、日志信息
        'verbose': {
            'format': '{levelname} {asctime} {module} {lineno:d} {message}',
            'style': '{',  # 使用新式字符串格式化
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # 控制台输出（开发环境用）
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        # 文件输出（生产环境用，日志会写入文件）
        'file': {
            'level': 'INFO',  # 日志级别：DEBUG < INFO < WARNING < ERROR < CRITICAL
            'class': 'logging.handlers.RotatingFileHandler',  # 按大小切割日志文件
            'filename': os.path.join(BASE_DIR, 'logs/iptv_admin.log'),  # 日志文件路径
            'maxBytes': 1024 * 1024 * 50,  # 单个日志文件最大50MB
            'backupCount': 5,  # 最多保留5个备份日志文件
            'formatter': 'verbose',  # 使用上面定义的verbose格式
            'encoding': 'utf-8',  # 防止中文乱码
        },
    },
    'loggers': {
        # 项目全局日志器（匹配所有日志）
        'django': {
            'handlers': ['console', 'file'],  # 同时输出到控制台+文件
            'level': 'INFO',
            'propagate': True,
        },
        # 针对adminApi应用的专属日志器（更精准）
        'adminApi': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # 不向上传播，避免重复日志
        },
    },
}
# ========== 日志配置结束 ==========
